const Vehicule =
  require('../models/Vehicule');

const seedVehicules =
  async (marques) => {

    await Vehicule.deleteMany();

    const getMarqueId =
      (nom) =>
        marques.find(
          (m) => m.nom === nom
        )._id;

    const vehicules = [
{
        marque: getMarqueId('Renault'),
        modele: 'Clio 5',
        prix: 58000,
        carburant: 'Essence',
        boiteVitesse: 'Manuelle',
        kilometrage: 45000,
        annee: 2022,
        typeVehicule: 'Citadine',
        nombrePlaces: 5,
        consommation: 4.8,
        description: 'Renault Clio économique',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Peugeot'),
        modele: '208',
        prix: 72000,
        carburant: 'Essence',
        boiteVitesse: 'Manuelle',
        kilometrage: 30000,
        annee: 2023,
        typeVehicule: 'Citadine',
        nombrePlaces: 5,
        consommation: 4.7,
        description: 'Peugeot 208 récente',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Toyota'),
        modele: 'Yaris',
        prix: 68000,
        carburant: 'Essence',
        boiteVitesse: 'Automatique',
        kilometrage: 25000,
        annee: 2023,
        typeVehicule: 'Citadine',
        nombrePlaces: 5,
        consommation: 4.5,
        description: 'Toyota Yaris fiable',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Volkswagen'),
        modele: 'Polo',
        prix: 78000,
        carburant: 'Essence',
        boiteVitesse: 'Automatique',
        kilometrage: 35000,
        annee: 2022,
        typeVehicule: 'Citadine',
        nombrePlaces: 5,
        consommation: 5.0,
        description: 'Volkswagen Polo',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Hyundai'),
        modele: 'i20',
        prix: 62000,
        carburant: 'Essence',
        boiteVitesse: 'Manuelle',
        kilometrage: 28000,
        annee: 2023,
        typeVehicule: 'Citadine',
        nombrePlaces: 5,
        consommation: 4.9,
        description: 'Hyundai i20',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Kia'),
        modele: 'Rio',
        prix: 61000,
        carburant: 'Essence',
        boiteVitesse: 'Manuelle',
        kilometrage: 40000,
        annee: 2022,
        typeVehicule: 'Citadine',
        nombrePlaces: 5,
        consommation: 5.1,
        description: 'Kia Rio économique',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Ford'),
        modele: 'Focus',
        prix: 85000,
        carburant: 'Diesel',
        boiteVitesse: 'Manuelle',
        kilometrage: 50000,
        annee: 2021,
        typeVehicule: 'Compacte',
        nombrePlaces: 5,
        consommation: 5.4,
        description: 'Ford Focus',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('BMW'),
        modele: 'Serie 3',
        prix: 135000,
        carburant: 'Diesel',
        boiteVitesse: 'Automatique',
        kilometrage: 30000,
        annee: 2022,
        typeVehicule: 'Berline',
        nombrePlaces: 5,
        consommation: 5.2,
        description: 'BMW Série 3',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Mercedes'),
        modele: 'Classe C',
        prix: 180000,
        carburant: 'Diesel',
        boiteVitesse: 'Automatique',
        kilometrage: 28000,
        annee: 2023,
        typeVehicule: 'Berline',
        nombrePlaces: 5,
        consommation: 5.6,
        description: 'Mercedes Classe C',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Audi'),
        modele: 'A4',
        prix: 170000,
        carburant: 'Diesel',
        boiteVitesse: 'Automatique',
        kilometrage: 32000,
        annee: 2022,
        typeVehicule: 'Berline',
        nombrePlaces: 5,
        consommation: 5.5,
        description: 'Audi A4',
        statut: 'Disponible',
        images: [],
        },
        {
        marque: getMarqueId('Volkswagen'),
        modele: 'Golf 7',
        prix: 95000,
        carburant: 'Diesel',
        boiteVitesse: 'Manuelle',
        kilometrage: 65000,
        annee: 2020,
        typeVehicule: 'Compacte',
        nombrePlaces: 5,
        consommation: 5.0,
        description: 'Volkswagen Golf 7',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Volkswagen'),
        modele: 'Tiguan',
        prix: 145000,
        carburant: 'Diesel',
        boiteVitesse: 'Automatique',
        kilometrage: 45000,
        annee: 2022,
        typeVehicule: 'SUV',
        nombrePlaces: 5,
        consommation: 6.2,
        description: 'Volkswagen Tiguan',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Toyota'),
        modele: 'Corolla',
        prix: 98000,
        carburant: 'Essence',
        boiteVitesse: 'Automatique',
        kilometrage: 35000,
        annee: 2022,
        typeVehicule: 'Berline',
        nombrePlaces: 5,
        consommation: 5.3,
        description: 'Toyota Corolla',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Toyota'),
        modele: 'RAV4',
        prix: 165000,
        carburant: 'Hybride',
        boiteVitesse: 'Automatique',
        kilometrage: 28000,
        annee: 2023,
        typeVehicule: 'SUV',
        nombrePlaces: 5,
        consommation: 5.7,
        description: 'Toyota RAV4 Hybride',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Hyundai'),
        modele: 'Tucson',
        prix: 135000,
        carburant: 'Diesel',
        boiteVitesse: 'Automatique',
        kilometrage: 42000,
        annee: 2022,
        typeVehicule: 'SUV',
        nombrePlaces: 5,
        consommation: 6.0,
        description: 'Hyundai Tucson',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Hyundai'),
        modele: 'Elantra',
        prix: 102000,
        carburant: 'Essence',
        boiteVitesse: 'Automatique',
        kilometrage: 33000,
        annee: 2023,
        typeVehicule: 'Berline',
        nombrePlaces: 5,
        consommation: 5.6,
        description: 'Hyundai Elantra',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Kia'),
        modele: 'Sportage',
        prix: 138000,
        carburant: 'Diesel',
        boiteVitesse: 'Automatique',
        kilometrage: 39000,
        annee: 2022,
        typeVehicule: 'SUV',
        nombrePlaces: 5,
        consommation: 6.1,
        description: 'Kia Sportage',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Kia'),
        modele: 'Cerato',
        prix: 92000,
        carburant: 'Essence',
        boiteVitesse: 'Automatique',
        kilometrage: 37000,
        annee: 2022,
        typeVehicule: 'Berline',
        nombrePlaces: 5,
        consommation: 5.5,
        description: 'Kia Cerato',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Ford'),
        modele: 'Kuga',
        prix: 128000,
        carburant: 'Diesel',
        boiteVitesse: 'Automatique',
        kilometrage: 48000,
        annee: 2021,
        typeVehicule: 'SUV',
        nombrePlaces: 5,
        consommation: 6.3,
        description: 'Ford Kuga',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Ford'),
        modele: 'Fiesta',
        prix: 59000,
        carburant: 'Essence',
        boiteVitesse: 'Manuelle',
        kilometrage: 52000,
        annee: 2021,
        typeVehicule: 'Citadine',
        nombrePlaces: 5,
        consommation: 5.0,
        description: 'Ford Fiesta',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('BMW'),
        modele: 'X3',
        prix: 195000,
        carburant: 'Diesel',
        boiteVitesse: 'Automatique',
        kilometrage: 25000,
        annee: 2023,
        typeVehicule: 'SUV',
        nombrePlaces: 5,
        consommation: 6.2,
        description: 'BMW X3',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('BMW'),
        modele: 'Serie 5',
        prix: 210000,
        carburant: 'Diesel',
        boiteVitesse: 'Automatique',
        kilometrage: 22000,
        annee: 2023,
        typeVehicule: 'Berline',
        nombrePlaces: 5,
        consommation: 5.9,
        description: 'BMW Série 5',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Mercedes'),
        modele: 'GLA',
        prix: 185000,
        carburant: 'Diesel',
        boiteVitesse: 'Automatique',
        kilometrage: 26000,
        annee: 2023,
        typeVehicule: 'SUV',
        nombrePlaces: 5,
        consommation: 6.0,
        description: 'Mercedes GLA',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Mercedes'),
        modele: 'Classe E',
        prix: 220000,
        carburant: 'Diesel',
        boiteVitesse: 'Automatique',
        kilometrage: 20000,
        annee: 2023,
        typeVehicule: 'Berline',
        nombrePlaces: 5,
        consommation: 5.8,
        description: 'Mercedes Classe E',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Audi'),
        modele: 'A3',
        prix: 125000,
        carburant: 'Diesel',
        boiteVitesse: 'Automatique',
        kilometrage: 40000,
        annee: 2022,
        typeVehicule: 'Compacte',
        nombrePlaces: 5,
        consommation: 5.1,
        description: 'Audi A3',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Audi'),
        modele: 'Q5',
        prix: 205000,
        carburant: 'Diesel',
        boiteVitesse: 'Automatique',
        kilometrage: 24000,
        annee: 2023,
        typeVehicule: 'SUV',
        nombrePlaces: 5,
        consommation: 6.3,
        description: 'Audi Q5',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Peugeot'),
        modele: '3008',
        prix: 125000,
        carburant: 'Diesel',
        boiteVitesse: 'Automatique',
        kilometrage: 41000,
        annee: 2022,
        typeVehicule: 'SUV',
        nombrePlaces: 5,
        consommation: 5.9,
        description: 'Peugeot 3008',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Peugeot'),
        modele: '508',
        prix: 118000,
        carburant: 'Diesel',
        boiteVitesse: 'Automatique',
        kilometrage: 47000,
        annee: 2021,
        typeVehicule: 'Berline',
        nombrePlaces: 5,
        consommation: 5.7,
        description: 'Peugeot 508',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Renault'),
        modele: 'Megane',
        prix: 88000,
        carburant: 'Diesel',
        boiteVitesse: 'Manuelle',
        kilometrage: 55000,
        annee: 2021,
        typeVehicule: 'Compacte',
        nombrePlaces: 5,
        consommation: 5.2,
        description: 'Renault Megane',
        statut: 'Disponible',
        images: [],
        },

        {
        marque: getMarqueId('Renault'),
        modele: 'Kadjar',
        prix: 115000,
        carburant: 'Diesel',
        boiteVitesse: 'Automatique',
        kilometrage: 50000,
        annee: 2021,
        typeVehicule: 'SUV',
        nombrePlaces: 5,
        consommation: 5.8,
        description: 'Renault Kadjar',
        statut: 'Disponible',
        images: [],
        },
        ];

    const created =
      await Vehicule.insertMany(
        vehicules
      );

    console.log(
      `✅ ${created.length} véhicules créés`
    );
};

module.exports =
  seedVehicules;